# Generated by Django 5.1.7 on 2025-03-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('politics', 'Politika'), ('sports', 'Spor'), ('economy', 'Ekonomi'), ('Business', 'İş Dünyası'), ('Technology', 'Teknoloji'), ('Science', 'Science'), ('Health', 'Sağlık')], default='politics', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('date_published', models.DateField()),
            ],
        ),
    ]
