# Generated by Django 5.1.7 on 2025-03-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taha', '0002_alter_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
