# Generated by Django 5.1.7 on 2025-03-23 03:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taha', '0004_category_aboutcontent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
