# Generated by Django 5.1.7 on 2025-03-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taha', '0005_alter_aboutcontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
