# Generated by Django 5.1.7 on 2025-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taha', '0006_aboutcontent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
