# Generated by Django 5.1.7 on 2025-03-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taha', '0007_alter_aboutcontent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
